/* GENERATED by tools/build.py from source/second_term_viva_question_bank_solved.md - do not edit by hand.
   This file holds the topic hierarchy only; question bodies live in topics/*.js. */
window.QB = window.QB || {};
QB.meta = {
 "title": "Second Term Viva Question Bank — Solved",
 "site": "Preventive & Social Medicine",
 "source": "second_term_viva_question_bank_solved.md",
 "totalQuestions": 80,
 "missingQuestions": 8
};
QB.structure = [
 {
  "id": "environment-and-health",
  "num": "1",
  "title": "Environment and Health",
  "heading": "1. Environment and Health",
  "questionIds": [],
  "subsections": [
   {
    "id": "environment-and-health--environment",
    "title": "Environment",
    "questionIds": [
     "q-b393f8e4"
    ]
   },
   {
    "id": "environment-and-health--water",
    "title": "Water",
    "questionIds": [
     "q-0845c2c1",
     "q-d27990b6",
     "q-18262d32",
     "q-2ed162b6",
     "q-8f1ecec0",
     "q-6c113534",
     "q-e9b8efb8",
     "q-6b0e531e"
    ]
   },
   {
    "id": "environment-and-health--air-and-ventilation",
    "title": "Air and Ventilation",
    "questionIds": [
     "q-23e54669",
     "q-829c639e",
     "q-27cfd37c",
     "q-11918a8f"
    ]
   },
   {
    "id": "environment-and-health--light",
    "title": "Light",
    "questionIds": [],
    "noteHtml": "<p><em>(No questions in the current question bank for this subtopic.)</em></p>"
   },
   {
    "id": "environment-and-health--noise",
    "title": "Noise",
    "questionIds": [],
    "noteHtml": "<p><em>(No questions in the current question bank for this subtopic.)</em></p>"
   },
   {
    "id": "environment-and-health--radiation",
    "title": "Radiation",
    "questionIds": [],
    "noteHtml": "<p><em>(No questions in the current question bank for this subtopic.)</em></p>"
   },
   {
    "id": "environment-and-health--housing",
    "title": "Housing",
    "questionIds": [],
    "noteHtml": "<p><em>(No questions in the current question bank for this subtopic.)</em></p>"
   },
   {
    "id": "environment-and-health--disposal-of-solid-waste",
    "title": "Disposal of Solid Waste",
    "questionIds": [
     "q-9d08fe8b",
     "q-660e1cc8",
     "q-48a0bd82"
    ]
   },
   {
    "id": "environment-and-health--excreta-disposal",
    "title": "Excreta Disposal",
    "questionIds": [
     "q-7975e240"
    ]
   }
  ]
 },
 {
  "id": "public-health-administration-and-management",
  "num": "2",
  "title": "Public Health Administration and Management",
  "heading": "2. Public Health Administration and Management",
  "questionIds": [
   "q-ca558cae",
   "q-0fa50f95",
   "q-eee289fb",
   "q-b27a7e96"
  ],
  "subsections": []
 },
 {
  "id": "epidemiology-of-non-communicable-and-communicable-diseases",
  "num": "3",
  "title": "Epidemiology of Non-Communicable and Communicable Diseases",
  "heading": "3. Epidemiology of Non-Communicable and Communicable Diseases",
  "questionIds": [],
  "subsections": [
   {
    "id": "epidemiology-of-non-communicable-and-communicable-diseases--general-epidemiology",
    "title": "General Epidemiology",
    "questionIds": [
     "q-91c192fe",
     "q-b984253a",
     "q-e267bf00",
     "q-91060a7b",
     "q-38d05f17",
     "q-912a53ad",
     "q-80c7347d",
     "q-d902b36a"
    ]
   },
   {
    "id": "epidemiology-of-non-communicable-and-communicable-diseases--non-communicable-diseases-ncds",
    "title": "Non-Communicable Diseases (NCDs)",
    "questionIds": [
     "q-d54154ab",
     "q-bd8c976f",
     "q-a801025d",
     "q-448055ca"
    ]
   },
   {
    "id": "epidemiology-of-non-communicable-and-communicable-diseases--communicable-diseases-cds",
    "title": "Communicable Diseases (CDs)",
    "questionIds": [
     "q-6795440c",
     "q-8e9673f1",
     "q-f8f0ace4",
     "q-ae3c2604",
     "q-c1f4b432",
     "q-752b2b2c",
     "q-e183da4a",
     "q-1e1bde9e",
     "q-c2832b0c",
     "q-69879ef5",
     "q-afbca050",
     "q-e229226f",
     "q-d9d3d571",
     "q-e04e18af",
     "q-6ce980df"
    ]
   }
  ]
 },
 {
  "id": "mch-fp-and-demography",
  "num": "4",
  "title": "MCH-FP and Demography",
  "heading": "4. MCH-FP and Demography",
  "questionIds": [],
  "subsections": [
   {
    "id": "mch-fp-and-demography--maternal-and-child-health-mch",
    "title": "Maternal and Child Health (MCH)",
    "questionIds": [
     "q-152039fe",
     "q-addb47d2",
     "q-108aa964",
     "q-ec45bf1a",
     "q-4dc6db15",
     "q-179cb10f",
     "q-4df5b046",
     "q-80cabae1",
     "q-c4df1c80"
    ]
   },
   {
    "id": "mch-fp-and-demography--family-planning-fp",
    "title": "Family Planning (FP)",
    "questionIds": [
     "q-99ce8943",
     "q-3d9d341b",
     "q-95184988",
     "q-7242185a",
     "q-e36ae23a",
     "q-bc1498c1",
     "q-9e4207db",
     "q-7deae30f",
     "q-1bed6ecc"
    ]
   },
   {
    "id": "mch-fp-and-demography--demography",
    "title": "Demography",
    "questionIds": [
     "q-b04f29e0",
     "q-21d59a6c",
     "q-604c832e",
     "q-202da6a7",
     "q-e5728fff"
    ]
   }
  ]
 },
 {
  "id": "school-health-services",
  "num": "5",
  "title": "School Health Services",
  "heading": "5. School Health Services",
  "questionIds": [
   "q-ecb829db",
   "q-b81d158c",
   "q-928a0d6a",
   "q-4bdb7818",
   "q-f53c5efe",
   "q-8bf2d64b"
  ],
  "subsections": []
 },
 {
  "id": "occupational-health",
  "num": "6",
  "title": "Occupational Health",
  "heading": "6. Occupational Health",
  "questionIds": [
   "q-8885f3ab",
   "q-53be8cea",
   "q-60ba5894",
   "q-45b177d9",
   "q-53491486",
   "q-99a161ff",
   "q-aabe39e0",
   "q-adadd993",
   "q-cd1a68a6",
   "q-33de5912",
   "q-3baba5b5"
  ],
  "subsections": []
 }
];
QB.questions = {};
QB.defineQuestions = function (list) {
  list.forEach(function (q) { QB.questions[q.id] = q; });
};
